### ISSUE TITLE
Support for tailwind Font Variant Numeric

### ISSUE THREAD

**Issue by chu121su12** [antfu/unocss#195]
Docs: https://tailwindcss.com/docs/font-variant-numeric

I tried to add the rules but it seems that the generator is prioritizing static rules and only returning the first rule that matches.

Is there planned update for the core to match more than 1 rule?

**Comment by chu121su12** [comment]
I am implementing the `font-variant-numeric` rules, and using tailwind as a reference, there's this section:

*(other modifiers are trimmed for brevity)*
```css
/* base */
.ordinal, .slashed-zero /*, ... */ {
  --tw-ordinal: var(--tw-empty,/*!*/ /*!*/);
  --tw-slashed-zero: var(--tw-empty,/*!*/ /*!*/);
  /* ... */
  font-variant-numeric: var(--tw-ordinal) var(--tw-slashed-zero) /* ... */;
}
/* modifiers */
.normal-nums { font-variant-numeric: normal; }
.ordinal { --tw-ordinal: ordinal; }
/* ... */
```

With the intention to copy this behaviour, I tried adding these rules:
```ts
const fontVariantNumericBase = {
  '--un-ordinal': varEmpty,
  '--un-slashed-zero': varEmpty,
  // ...
  'font-variant-numeric': 'var(--un-ordinal) var(--un-slashed-zero)', //...
}
const fontVariantNumericV1: Rule[] = [
  [/^(?:ordinal|slashed-zero|___)$/, () => fontVariantNumericBase],
  ['normal-nums', { 'font-variant-numeric': 'normal' }],
  ['ordinal', { '--tw-ordinal': 'ordinal' }],
  ['slashed-zero', { '--tw-slashed-zero': 'slashed-zero' }],
  // ...
]
```

The generator prioritizing string rules only produced the css in `modifiers` section. By allowing multiple matches, this can be achieved with the V1 rules.

Although, while writing this comment, I remember you can just use this V2 rules:
```ts
const handleFontVariantNumeric = (style: object) => ({
  ...fontVariantNumericBase,
  ...style,
})
const fontVariantNumericV2: Rule[] = [
  ['ordinal', handleFontVariantNumeric({ '--tw-ordinal': 'ordinal' })],
  ['slashed-zero', handleFontVariantNumeric({ '--tw-slashed-zero': 'slashed-zero' })],
  // ...
  // 'normal-nums' moved to bottom as this should override the `base` css
  ['normal-nums', { 'font-variant-numeric': 'normal' }], 
]
```
Albeit with slightly repetitive css outputs:
```css
.ordinal{
    --un-ordinal:var(--un-empty,/*!*/ /*!*/); /* ... base css */
    font-variant-numeric:var(--un-ordinal)    /* ... base css */ ;
    --un-ordinal:ordinal;}
.slashed-zero{
    --un-ordinal:var(--un-empty,/*!*/ /*!*/); /* ... base css again */
    font-variant-numeric:var(--un-ordinal)    /* ... base css again */ ;
    --un-slashed-zero:slashed-zero;}
/* ... more modifiers */
.normal-nums{font-variant-numeric:normal;}
```

---

This may be further leaning into tailwind's jit concept, but in the jit docs theres [this](https://tailwindcss.com/docs/just-in-time-mode#simplified-transform-filter-and-backdrop-filter-composition):
```html
- <div class="transform scale-50 filter grayscale backdrop-filter backdrop-blur-sm">
+ <div class="scale-50 grayscale backdrop-blur-sm">
```
This is my original thought of reference when opening this issue; that is to be able to automatically add, for example: `transform`, `filter`, or `backdrop-filter` definition when using the related classes.

Also, I've finished my modification for this feature: [branch](https://github.com/chu121su12/unocss/commits/multiple-match), [commit](https://github.com/chu121su12/unocss/commit/0f218b1c466d0c724af86ac092a3450a7ba046f0).
