### ISSUE TITLE
Default border-color override (reset/preset-uno)

### ISSUE THREAD

**Issue by chu121su12** [antfu/unocss#200]
By default, using divide border utility (I think this also applies to any border utility) without specifying divide color will use `currentcolor` due to `border-color` rule in the reset:

https://github.com/antfu/unocss/blob/ba147e83b36fc333ba3f514671cd8545576fb9ef/packages/reset/tailwind.css#L6-L13

![image](https://user-images.githubusercontent.com/379924/144351198-7a602f04-57e1-42ad-b487-e25a34813608.png)

In a compiled tailwind, there's this global border override of color `gray-200` just after the `preflight.css`:
```css
*, ::before, ::after {
  --tw-border-opacity: 1;
  border-color: rgba(229, 231, 235, var(--tw-border-opacity));
}
```
Thus producing this output instead:
![image](https://user-images.githubusercontent.com/379924/144352260-4298995d-3563-4beb-ba89-34737d6a8ca8.png)

Is there any plan to add this rule to reset or uno-preset?
