### ISSUE TITLE
Attributify: attribute: `group`'s selector doesn't match

### ISSUE THREAD

**Issue by UltraCakeBakery** [antfu/unocss#229]
The generated selector for the `group` attribute does not match. 

Input:
```html
<div group>
      <div opacity-0 group-hover:opacity-100
</div>
```

Output:
```css
.group:hover [group-hover~="opacity-100"],.opacity-100{opacity:1;}
```
