### ISSUE TITLE
Unstable print variant output

### ISSUE THREAD

**Issue by chu121su12** [antfu/unocss#323]
Adding print variant In #314, the generated output is unstable.

```css
    .will-change-unset{will-change:unset;}
  + @media print{
  + .print\:block{display:block;}
  + .print\:link\:\!underline:link{text-decoration:underline !important;}
  + }
    @media (prefers-color-scheme: dark){
    .dark\:text-xl{font-size:1.25rem;line-height:1.75rem;}
    .dark\:not-odd\:text-red:not(:nth-child(odd)){--un-text-opacity:1;color:rgba(248,113,113,var(--un-text-opacity));}
    }
    @media (prefers-color-scheme: light){
    .light\:text-sm{font-size:0.875rem;line-height:1.25rem;}
    }
  - @media print{
  - .print\:block{display:block;}
  - .print\:link\:\!underline:link{text-decoration:underline !important;}
  - }
    @media (max-width: 1024px){
    .lt-lg\:m2{margin:0.5rem;}
    }
```

When generated with multiple generator instance or tested the 2nd vs 3rd time, the test passes.

```js
await uno.generate(code)
expect(await uno.generate(code).css).toEqual(await uno.generate(code).css)
```
