### ISSUE TITLE
[@unocss/preset-uno]: Unable to set font-size to `base`

### ISSUE THREAD

**Issue by DerYeger** [antfu/unocss#510]
I want smaller text size on mobile screens and thus use `text-sm`. For `sm` and up I want the `base` size, but neither `sm-text-base` nor `sm-text-size-base` nor `sm-text-base` nor `sm-text-size` works.
 `sm-text-xl` works fine but is of course not the `base` size I need.
 
 Edit:
 I checked the inspector (from [this repository](https://github.com/DerYeger/jan-mueller/blob/next/src/components/Main.vue)) and had the following CSS generated (notice that there's no media query):
 ```css
 .text-sm{font-size:0.875rem;line-height:1.25rem;}
 .sm-text-base{--un-text-opacity:1;color:rgba(0,0,0,var(--un-text-opacity));}
 ```
 
 Meanwhile, [the playground](https://unocss.antfu.me/?html=DwBwBAxgNghgznAvAIgC4FMAeqC0cC2YBOG2OARvOsgHwBQYYAKunKncAPQg1A&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA) has different CSS generated:
 ```css
 /* layer: default */
.text-sm{font-size:0.875rem;line-height:1.25rem;}
@media (min-width: 640px){
.sm-text-base{font-size:1rem;line-height:1.5rem;}
}
 ```
